### ISSUE TITLE
Text disappears in some situations

### ISSUE THREAD

**Issue by Felix14-v2** [cbyrneee/compact-chat#19]
**To reproduce**
Try to use `/execute if block ~ ~ ~ minecraft:void_air` several times

**Info**
- Minecraft 1.19
- CompactChat 1.3
- Other mods that doesn't affect chat (most likely)

**Additional**
[[Demo]](https://youtu.be/_KIcOY0B5Rk)

**Comment by cbyrneee** [comment]
Thanks for the report :)

**Comment by cbyrneee** [comment]
Fixed in cbda1de, will close when released.
