### ISSUE TITLE
1.19.2?

### ISSUE THREAD

**Issue by Aces-and-Jacks** [cbyrneee/compact-chat#22]
Is this planned at some point?

**Comment by cbyrneee** [comment]
I am working on this right now :)

**Comment by cbyrneee** [comment]
I lied, I am *now* working on this! Check the 2.x branch.

**Comment by cbyrneee** [comment]
This has been released as version 2.0.0 @Aces-and-Jacks!

https://modrinth.com/mod/compact-chat/version/2.0.0
